apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-history-fetch
  namespace: argocd
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deploy-history-reader
          restartPolicy: OnFailure
          containers:
            - name: fetch
              image: gitea.hermitden/virtualhermit/deploy-history-fetch:latest
      backoffLimit: 2
      
      