apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-history
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PelmeenidHapukoorega/CI-CD-DevOps.git
    targetRevision: main
    path: Homelabing/Ingress-page/metrics/deploy-history/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true