pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
    - name: registry-creds
      mountPath: /kaniko/.docker
    - name: hermitden-ca
      mountPath: /kaniko/ssl/certs/hermitden-ca.crt
      subPath: ca.crt
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  volumes:
  - name: registry-creds
    secret:
      secretName: gitea-registry-secret
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: hermitden-ca
    configMap:
        name: hermitden-ca
"""
    }
  }

  options {
    disableConcurrentBuilds()
  }

  environment {
    IMAGE = "gitea.hermitden/virtualhermit/hermitden-site"
    MANIFEST_PATH = "Homelabing/Ingress-page/manifests/site-deployment.yaml"
  }

  stages {
    stage('Skip if bot commit') {
      steps {
        script {
          def msg = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
          if (msg.startsWith("deploy:")) {
            error("bot commit, skipping")
          }
        }
      }
    }
    stage('Build and push image') {
      when {
        changeset "Homelabing/Ingress-page/**"
      }
      steps {
        container('kaniko') {
          sh """
            /kaniko/executor \
              --context=`pwd`/Homelabing/Ingress-page/Page-assets \
              --dockerfile=dockerfile \
              --registry-certificate=gitea.hermitden=/kaniko/ssl/certs/hermitden-ca.crt \
              --destination=${IMAGE}:${GIT_COMMIT.take(7)}
          """
        }
      }
    }
    stage('Build and push deploy-history-fetch image') {
      when {
        anyOf {
          changeset "Homelabing/Ingress-page/metrics/deploy-history/dockerfile"
          changeset "Homelabing/Ingress-page/metrics/deploy-history/fetch.sh"
        }
      }
      steps {
        container('kaniko') {
          sh """
            /kaniko/executor \
              --context=`pwd`/Homelabing/Ingress-page/metrics/deploy-history \
              --dockerfile=dockerfile \
              --registry-certificate=gitea.hermitden=/kaniko/ssl/certs/hermitden-ca.crt \
              --destination=gitea.hermitden/virtualhermit/deploy-history-fetch:latest
          """
        }
      }
    }
    stage('Update manifest') {
      when {
        changeset "Homelabing/Ingress-page/**"
      }
      steps {
        sh """
          sed -i -E 's|^([[:space:]]*)image: .*|\\1image: ${IMAGE}:${GIT_COMMIT.take(7)}|' ${MANIFEST_PATH}
        """
      }
    }
    stage('Commit manifest change') {
      when {
        changeset "Homelabing/Ingress-page/**"
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'github-write-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
          sh '''
            git config user.email "jenkins@hermitden.dev"
            git config user.name "jenkins"
            git add ''' + MANIFEST_PATH + '''
            git commit -m "deploy: hermitden-site ''' + GIT_COMMIT.take(7) + '''"
            git push https://$GIT_USER:$GIT_PASS@github.com/PelmeenidHapukoorega/CI-CD-DevOps.git HEAD:main
          '''
        }
      }
    }
  }
}