pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
    - name: registry-creds
      mountPath: /kaniko/.docker
    - name: hermitden-ca
      mountPath: /kaniko/ssl/certs/hermitden-ca.crt
      subPath: ca.crt
  volumes:
  - name: registry-creds
    secret:
      secretName: gitea-registry-secret
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: hermitden-ca
    configMap:
        name: hermitden-ca
"""
    }
  }

  triggers {
    githubPush()
  }

  environment {
    IMAGE = "gitea.hermitden/virtualhermit/hermitden-site"
    MANIFEST_PATH = "Homelabing/Ingress-page/manifests/site-deployment.yaml"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and push image') {
      steps {
        container('kaniko') {
          sh """
            /kaniko/executor \
              --context=`pwd`/Homelabing/Ingress-page/Page-assets \
              --dockerfile=dockerfile \
              --registry-certificate=gitea.hermitden=/kaniko/ssl/certs/hermitden-ca.crt \
              --destination=${IMAGE}:${GIT_COMMIT.take(7)}
          """
        }
      }
    }

    stage('Update manifest') {
      steps {
        sh """
          sed -i -E 's|^([[:space:]]*)image: .*|\\1image: ${IMAGE}:${GIT_COMMIT.take(7)}|' ${MANIFEST_PATH}
        """
      }
    }

stage('Commit manifest change') {
  steps {
    withCredentials([usernamePassword(credentialsId: 'github-write-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
      sh '''
        git config user.email "jenkins@hermitden.dev"
        git config user.name "jenkins"
        git add ''' + MANIFEST_PATH + '''
        git commit -m "deploy: hermitden-site ''' + GIT_COMMIT.take(7) + '''"
        git push https://$GIT_USER:$GIT_PASS@github.com/PelmeenidHapukoorega/CI-CD-DevOps.git HEAD:main
      '''
    }
  }
}
  }
}